#!/bin/bash

reset

# Load information and settings

echo "Loading..."
BASEDIR=$(dirname $0)
CONFIGFILE=~/.config/dynmotd.conf
if [ ! -d ~/.config ];
then
    mkdir ~/.config
fi
if [ ! -f $CONFIGFILE ];
then
    echo -e "# Set options for main script\n# ZIP Code (For weather)\nZIP=11234\n# Print banner (1=yes, 0=no)\nPRINTBAN=1\n# Print a custom banner (1=yes, 0=no)\nCUSTBAN=0\n# Text to be displayed in custom banner (backticks and \ escapes are allowed, use \n to end a line)\nCUSTBANTEXT=""\n# Which banner to print (BANLINUX, BANLINUXBIG, BANUBUNTU, BANANDROID, or BANMACOSX)\nBANNER=BANLINUX" >>$CONFIGFILE
fi
source $CONFIGFILE
TIME=`date`
HOST=`hostname`
WIFIADDR=`ifconfig wlan0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
ETHADDR=`ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
KERNELVER=`uname -r`
USERSTATS=`w`
MEMSIZE=`cat /proc/meminfo | grep MemTotal | awk {'print $2'}`
USER=`whoami`
LASTLOGIN=`last -n 2 -R $USER | awk 'NR==2'`
PROCOUNT=`ps -Afl | wc -l`
PROLIMIT=`ulimit -u`
USERDIR=`echo ~`
WLOC=`weather $ZIP | grep 'Current conditions at' | awk '{print $4}'`
WTEMP=`weather $ZIP | grep 'Temperature:' | awk '{print $2}'`
WCOND=`weather $ZIP | grep 'Weather:' | cut -d: -f2 | cut -c2-`
WSKY=`weather $ZIP | grep 'Sky conditions:' | cut -d: -f2 | cut -c2-`

echo "Done!"
reset

#Begin Driplay

if [[ $PRINTBAN == 1 ]]
then
    if [[ $CUSTBAN == 1 ]]
    then
        echo -e $CUSTBANTEXT
    else

    if [[ $BANNER == BANLINUXBIG ]]
    then
        echo -e "\033[1;37m __       __   __   __   __    __  ___   ___
|  |     |  | |  \ |  | |  |  |  | \  \ /  /
|  |     |  | |   \|  | |  |  |  |  \  \u203e  /
|  |____ |  | |  . .  | |  |  |  |   >   <
|       ||  | |  |\   | |  |__|  |  /  _  \ 
|_______||__| |__| \__|  \______/  /__/ \__\ 
"
    fi

    if [[ $BANNER == BANUBUNTU ]]
    then
        echo -e "\033[1;37m   __  ____                __
  / / / / /_  __  ______  / /___  __
 / / / / __ \/ / / / __ \/ __/ / / /
/ /_/ / /_/ / /_/ / / / / /_/ /_/ /
\____/_____/\____/_/ /_/\__/\____/
"
    fi

    if [[ $BANNER == BANLINUX ]]
    then
        echo -e "\033[1;37m    __    _
   / /   /_/___  __  ___  __
  / /   / / __ \/ / / / |/ /
 / /___/ / / / / /_/ /|   |
/_____/_/_/ /_/\____//_/\_\ 
"
    fi

    if [[ $BANNER == BANANDROID ]]
    then
        echo -e "\033[1;37m    ___              __           __    __
   /   |  ____  ____/ /________  /_/___/ /
  / /| | / __ \/ __  / ___/ __ \/ / __  /
 / ___ |/ / / / /_/ / /  / /_/ / / /_/ /
/_/  |_/_/ /_/\____/_/   \____/_/\____/
"
    fi

    if [[ $BANNER == BANMACOSX ]]
    then
        echo -e "\033[1;37m    __  ___              ____  _____    _  __
   /  |/  /__________   / __ \/ ___/   | |/ /
  / /|_/ / __  / ___/  / / / /\__ \    |   /
 / /  / / /_/ / /__   / /_/ /___/ /   /   |
/_/  /_/\____/\___/   \____//____/   /_/|_|
"
    fi
    fi
fi
echo -e "\033[0;36m:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=[ \033[1;31mSystem Stats \033[0;36m]=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:
\033[0;36m: \033[1;37mDate/Time \033[0;36m= \033[1;32m$TIME
\033[0;36m:  \033[1;37mHostname \033[0;36m= \033[1;32m$HOST
\033[0;36m:   \033[1;37mWLAN IP \033[0;36m= \033[1;32m$WIFIADDR
\033[0;36m:    \033[1;37mLAN IP \033[0;36m= \033[1;32m$ETHADDR
\033[0;36m:    \033[1;37mKernel \033[0;36m= \033[1;32m$KERNELVER
\033[0;36m:    \033[1;37mMemory \033[0;36m= \033[1;32m$MEMSIZE kB
\033[0;36m:     \033[1;37mStats \033[0;36m= \033[1;32m$USERSTATS
\033[0;36m:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:[ \033[1;31mUser Stats \033[0;36m]:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:
\033[0;36m:  \033[1;37mUsername \033[0;36m= \033[1;32m$USER
\033[0;36m:\033[1;37mLast Login \033[0;36m= \033[1;32m$LASTLOGIN
\033[0;36m: \033[1;37mProcesses \033[0;36m= \033[1;32m$PROCOUNT of $PROLIMIT
\033[0;36m:      \033[1;37mHome \033[0;36m= \033[1;32m$USERDIR
\033[0;36m:=:=:=:=:=:=:=:=:=:=:=:=:=:[ \033[1;31mInternet Weather Stats \033[0;36m]:=:=:=:=:=:=:=:=:=:=:=:=:=:
\033[0;36m:  \033[1;37mLocation \033[0;36m= \033[1;32m$WLOC, $ZIP
\033[0;36m:      \033[1;37mTemp \033[0;36m= \033[1;32m$WTEMP \u00b0F
\033[0;36m:   \033[1;37mWeather \033[0;36m= \033[1;32m$WCOND
\033[0;36m:       \033[1;37mSky \033[0;36m= \033[1;32m$WSKY
\033[0;36m:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:[]:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:
\033[0;0m"
